/**
 * @file database.h
 * @brief SQLite database wrapper for TOTP account management
 *
 * This class provides a simple interface for storing and retrieving
 * TOTP accounts from an SQLite database.
 *
 * Database Schema:
 *   - accounts table: stores all TOTP account information
 *
 * @author TanmoyTheBoT
 * @date 2026-09-12
 */

#ifndef DATABASE_H
#define DATABASE_H

#include <string>
#include <vector>
#include "account.h"

/**
 * @class Database
 * @brief SQLite database manager for TOTP accounts
 *
 * Handles all database operations including:
 * - Creating/opening database file
 * - Creating tables
 * - CRUD operations (Create, Read, Update, Delete) for accounts
 *
 * Usage Example:
 *   Database db;
 *   if (db.open("accounts.db")) {
 *       db.createTables();
 *       Account acc;
 *       acc.issuer = "Google";
 *       acc.username = "user@gmail.com";
 *       acc.secret = "BASE32SECRET";
 *       db.addAccount(acc);
 *   }
 */
class Database
{
public:
    /**
     * @brief Constructor - initializes database pointer
     */
    Database();

    /**
     * @brief Destructor - automatically closes database connection
     */
    ~Database();

    /**
     * @brief Open or create a database file
     *
     * If the file doesn't exist, SQLite will create it.
     * You must call createTables() after opening a new database.
     *
     * @param filename Path to database file (e.g., "accounts.db")
     * @return true if successful, false on error
     *
     * @example
     *   Database db;
     *   if (!db.open("data/accounts.db")) {
     *       std::cerr << "Failed to open database!" << std::endl;
     *   }
     */
    bool open(const std::string& filename);

    /**
     * @brief Close the database connection
     *
     * Called automatically by destructor.
     * All operations will fail after calling this.
     */
    void close();

    /**
     * @brief Create the accounts table if it doesn't exist
     *
     * Table Schema:
     *   id       INTEGER PRIMARY KEY AUTOINCREMENT
     *   issuer   TEXT NOT NULL          (Service name: Google, GitHub, etc.)
     *   username TEXT NOT NULL          (Account email/username)
     *   secret   TEXT NOT NULL          (Base32 secret key)
     *   algorithm TEXT DEFAULT 'SHA1'  (SHA1, SHA256, or SHA512)
     *   digits   INTEGER DEFAULT 6      (OTP length: 6 or 8)
     *   period   INTEGER DEFAULT 30     (Time step: 30 or 60 seconds)
     *   notes    TEXT DEFAULT ''        (User notes)
     *   favorite INTEGER DEFAULT 0      (Favorite flag: 0 or 1)
     *
     * @return true if table created or already exists, false on error
     */
    bool createTables();

    /**
     * @brief Add a new account to the database
     *
     * The account.id field is ignored and auto-generated by SQLite.
     *
     * @param account Account object with details to insert
     * @return true if successfully added, false on error
     *
     * @example
     *   Account acc;
     *   acc.issuer = "Google";
     *   acc.username = "user@gmail.com";
     *   acc.secret = "JBSWY3DPEHPK3PXP";
     *   acc.algorithm = "SHA1";
     *   acc.digits = 6;
     *   acc.period = 30;
     *   if (db.addAccount(acc)) {
     *       std::cout << "Account added!" << std::endl;
     *   }
     */
    bool addAccount(const Account& account);

    /**
     * @brief Update an existing account
     *
     * Updates all fields for the account with matching ID.
     * The account.id field must be set to an existing account ID.
     *
     * @param account Account object with updated details
     * @return true if successfully updated, false on error or ID not found
     */
    bool updateAccount(const Account& account);

    /**
     * @brief Delete an account by ID
     *
     * Permanently removes the account from the database.
     * This operation cannot be undone!
     *
     * @param id Account ID to delete
     * @return true if successfully deleted, false on error or ID not found
     */
    bool deleteAccount(int id);

    /**
     * @brief Retrieve all accounts from the database
     *
     * Returns all accounts sorted by ID.
     * The returned vector will be empty if no accounts exist.
     *
     * @return Vector of Account objects
     *
     * @example
     *   std::vector<Account> accounts = db.getAccounts();
     *   for (const auto& acc : accounts) {
     *       std::cout << acc.issuer << ": " << acc.username << std::endl;
     *   }
     */
    std::vector<Account> getAccounts();

private:
    // Prevent copying (database connections shouldn't be copied)
    Database(const Database&) = delete;
    Database& operator=(const Database&) = delete;

    /**
     * @brief SQLite database handle
     *
     * Stored as void* to avoid exposing SQLite types in the header.
     * Internally this is a sqlite3* pointer.
     */
    void* db;
};

#endif // DATABASE_H
